-- RetainFlow - Phase 1 ML schema and tables
-- This file is intentionally repeated before ML generation so reruns are robust
-- even when the initial Unity Catalog model was created from an older version.

CREATE SCHEMA IF NOT EXISTS retainflow.ml
COMMENT 'Churn feature tables, labels, model outputs, and scoring results.';

CREATE TABLE IF NOT EXISTS retainflow.ml.churn_feature_snapshot (
  observation_date DATE COMMENT 'Feature observation date.',
  customer_id STRING COMMENT 'Logical FK to silver.dim_customer.customer_id.',
  tenure_months INT,
  active_policy_count INT,
  number_of_products INT,
  total_annual_premium DOUBLE,
  total_claims_12m INT,
  total_claim_amount_12m DOUBLE,
  payment_incidents_6m INT,
  complaints_6m INT,
  interactions_3m INT,
  days_since_last_contact INT,
  digital_sessions_30d INT,
  email_open_rate_6m DOUBLE,
  premium_increase_pct_max_12m DOUBLE,
  avg_satisfaction_score_12m DOUBLE,
  renewal_days_min INT,
  customer_value_score DOUBLE,
  customer_segment STRING,
  estimated_income_band STRING,
  digital_profile STRING,
  price_sensitivity_score DOUBLE,
  digital_engagement_score DOUBLE,
  loyalty_score DOUBLE,
  created_at TIMESTAMP
)
USING DELTA
COMMENT 'ML-ready churn feature snapshot built without using post-observation future information.';

CREATE TABLE IF NOT EXISTS retainflow.ml.churn_labels (
  observation_date DATE COMMENT 'Feature observation date.',
  customer_id STRING COMMENT 'Logical FK to silver.dim_customer.customer_id.',
  prediction_horizon_days INT,
  churn_label INT COMMENT '1 if customer churns in the prediction horizon, else 0.',
  churn_probability DOUBLE COMMENT 'Synthetic churn probability generated from business signals.',
  churn_risk_band STRING COMMENT 'LOW, MEDIUM, HIGH, or VERY_HIGH.',
  label_reason STRING COMMENT 'Dominant synthetic churn driver.',
  created_at TIMESTAMP
)
USING DELTA
COMMENT 'Synthetic churn labels for future supervised ML experiments.';

CREATE TABLE IF NOT EXISTS retainflow.ml.churn_predictions (
  observation_date DATE COMMENT 'Feature observation date.',
  customer_id STRING COMMENT 'Scored customer identifier.',
  churn_probability DOUBLE COMMENT 'Predicted probability of churn.',
  predicted_churn_label INT COMMENT 'Predicted churn class from the configured threshold.',
  churn_risk_band STRING COMMENT 'LOW, MEDIUM, HIGH, or VERY_HIGH.',
  model_name STRING,
  model_version STRING,
  scoring_run_id STRING,
  scored_at TIMESTAMP
)
USING DELTA
COMMENT 'Batch churn scores generated by the churn model pipeline.';
