import type { RetainFlowRow } from "./api";

export const sampleCustomers: RetainFlowRow[] = [
  {
    customer_id: "CUST_000123",
    first_name: "Nadia",
    last_name: "Martin",
    customer_segment: "Premium",
    region: "Ile-de-France",
    priority_tier: "CRITICAL",
    priority_score: 94.2,
    churn_probability: 0.87,
    expected_saved_value: 3200,
    total_annual_premium: 2420,
    recommended_action_type: "Priority resolution call",
    recommended_channel: "Phone",
    recommended_offer: "Controlled loyalty discount",
    next_best_step: "Assign a senior advisor within 24 hours.",
    decision_rationale: "High churn probability, recent premium increase, and declining loyalty score.",
    loyalty_score: 0.34,
    price_sensitivity_score: 0.82,
    service_sensitivity_score: 0.71,
    payment_incidents_6m: 0,
    complaints_6m: 2,
    renewal_days_min: 18,
    days_since_last_contact: 72,
  },
  {
    customer_id: "CUST_000831",
    first_name: "Thomas",
    last_name: "Moreau",
    customer_segment: "Standard",
    region: "Auvergne-Rhone-Alpes",
    priority_tier: "HIGH",
    priority_score: 88.5,
    churn_probability: 0.81,
    expected_saved_value: 1850,
    total_annual_premium: 1680,
    recommended_action_type: "Renewal save call",
    recommended_channel: "Phone",
    recommended_offer: "Payment plan adjustment",
    next_best_step: "Schedule outbound call before renewal.",
    decision_rationale: "Renewal is near and engagement has dropped.",
    loyalty_score: 0.42,
    price_sensitivity_score: 0.64,
    service_sensitivity_score: 0.48,
    payment_incidents_6m: 1,
    complaints_6m: 0,
    renewal_days_min: 24,
    days_since_last_contact: 96,
  },
  {
    customer_id: "CUST_000452",
    first_name: "Camille",
    last_name: "Bernard",
    customer_segment: "Premium",
    region: "Nouvelle-Aquitaine",
    priority_tier: "HIGH",
    priority_score: 85.9,
    churn_probability: 0.76,
    expected_saved_value: 2750,
    total_annual_premium: 2190,
    recommended_action_type: "Proactive retention check",
    recommended_channel: "Email + advisor follow-up",
    recommended_offer: "Assisted digital reactivation",
    next_best_step: "Create an advisor task for qualification.",
    decision_rationale: "Low digital engagement and recent service friction.",
    loyalty_score: 0.46,
    price_sensitivity_score: 0.52,
    service_sensitivity_score: 0.67,
    payment_incidents_6m: 0,
    complaints_6m: 1,
    renewal_days_min: 41,
    days_since_last_contact: 128,
  },
  {
    customer_id: "CUST_000677",
    first_name: "Amine",
    last_name: "Petit",
    customer_segment: "Family",
    region: "Occitanie",
    priority_tier: "MEDIUM",
    priority_score: 68.4,
    churn_probability: 0.58,
    expected_saved_value: 1260,
    total_annual_premium: 1210,
    recommended_action_type: "Digital re-engagement",
    recommended_channel: "Email",
    recommended_offer: "Coverage review",
    next_best_step: "Trigger a personalized campaign.",
    decision_rationale: "Moderate risk with weak recent contact history.",
    loyalty_score: 0.57,
    price_sensitivity_score: 0.44,
    service_sensitivity_score: 0.39,
    payment_incidents_6m: 0,
    complaints_6m: 0,
    renewal_days_min: 63,
    days_since_last_contact: 144,
  },
];

export const riskDistribution = [
  { name: "High", customers: 128, color: "#dc2626" },
  { name: "Medium", customers: 244, color: "#d97706" },
  { name: "Low", customers: 628, color: "#059669" },
];

export const riskTrend = [
  { week: "W-5", risk: 0.61, action: 42 },
  { week: "W-4", risk: 0.64, action: 51 },
  { week: "W-3", risk: 0.59, action: 49 },
  { week: "W-2", risk: 0.67, action: 64 },
  { week: "W-1", risk: 0.71, action: 73 },
  { week: "Now", risk: 0.68, action: 69 },
];
